/**
 * Component: TeamDisplay.jsx
 * Purpose: Display generated teams from backend API
 * Part of: Easter Quest 2025 Team Creation
 * Location: frontend/src/components/TeamCreation/TeamDisplay.jsx
 * 
 * Features:
 * - Display teams generated by backend algorithm
 * - Show team members with departments
 * - Highlight team captain
 * - Team statistics summary
 * - Export teams to CSV via API service
 * - Empty state when no teams exist
 * 
 * Data Structure Expected from Backend:
 * teams: [{
 *   id: number,
 *   name: string,
 *   leader_id: number,
 *   members: [{id, username, display_name, department}]
 * }]
 * 
 * @since 2025-08-31
 */

import React, { useState } from 'react';
import api from '../../services/api';

const TeamDisplay = ({ teams, players, showNotification, useMock = false }) => {
  const [exportLoading, setExportLoading] = useState(false);

  /**
   * Calculate team statistics from real backend data
   */
  const calculateStats = () => {
    if (!teams || teams.length === 0) {
      return {
        totalTeams: 0,
        totalPlayers: 0,
        avgTeamSize: 0,
        minTeamSize: 0,
        maxTeamSize: 0,
        departmentDistribution: {}
      };
    }

    const totalPlayers = teams.reduce((sum, team) => sum + (team.members?.length || 0), 0);
    const teamSizes = teams.map(team => team.members?.length || 0);
    const minTeamSize = Math.min(...teamSizes);
    const maxTeamSize = Math.max(...teamSizes);
    const avgTeamSize = totalPlayers > 0 ? (totalPlayers / teams.length) : 0;

    // Calculate department distribution
    const departmentDistribution = {};
    teams.forEach(team => {
      (team.members || []).forEach(member => {
        const dept = member.department || 'Unassigned';
        departmentDistribution[dept] = (departmentDistribution[dept] || 0) + 1;
      });
    });

    return {
      totalTeams: teams.length,
      totalPlayers,
      avgTeamSize: Math.round(avgTeamSize * 10) / 10,
      minTeamSize,
      maxTeamSize,
      departmentDistribution
    };
  };

  /**
   * Handle CSV export via backend API
   */
  const handleExportCSV = async () => {
    if (!teams || teams.length === 0) {
      showNotification('No teams to export', 'warning');
      return;
    }

    setExportLoading(true);
    
    try {
      const csvData = await api.teams.export();
      
      // Create and download CSV file
      const blob = new Blob([csvData], { type: 'text/csv;charset=utf-8' });
      const link = document.createElement('a');
      const url = URL.createObjectURL(blob);
      
      link.href = url;
      link.download = `team-assignments-${new Date().toISOString().split('T')[0]}.csv`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      showNotification('Teams exported successfully', 'success');
      
    } catch (error) {
      api.utils.handleError(error, showNotification);
    } finally {
      setExportLoading(false);
    }
  };

  /**
   * Get captain for a team
   */
  const getTeamCaptain = (team) => {
    if (!team.members || !team.leader_id) return null;
    return team.members.find(member => member.id === team.leader_id);
  };

  const stats = calculateStats();

  // Empty state - no teams generated yet
  if (!teams || teams.length === 0) {
    return (
      <div className="card">
        <div className="card-header">
          <h3 className="card-title">Generated Teams</h3>
        </div>
        <div className="card-body">
          <div className="empty-state">
            <div className="empty-icon">🎲</div>
            <h4>No Teams Created Yet</h4>
            <p>Configure your team settings and click "Create Teams" to generate teams using the backend algorithm.</p>
            <div className="empty-hints">
              <small>Steps:</small>
              <ul>
                <li>Upload players using CSV file</li>
                <li>Configure team size and department constraints</li>
                <li>Backend will create balanced teams automatically</li>
                <li>Captains assigned based on your rules</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="card">
      <div className="card-header">
        <div className="card-title-section">
          <h3 className="card-title">Generated Teams ({teams.length})</h3>
          <div className="header-actions">
            <button
              className="btn btn-primary"
              onClick={handleExportCSV}
              disabled={exportLoading}
            >
              {exportLoading ? 'Exporting...' : 'Export CSV'}
            </button>
          </div>
        </div>
      </div>

      <div className="card-body">
        
        {/* Team Statistics */}
        <div className="team-stats">
          <h4>Team Statistics</h4>
          <div className="stats-grid">
            <div className="stat-item">
              <span className="stat-value">{stats.totalTeams}</span>
              <span className="stat-label">Teams</span>
            </div>
            <div className="stat-item">
              <span className="stat-value">{stats.totalPlayers}</span>
              <span className="stat-label">Players</span>
            </div>
            <div className="stat-item">
              <span className="stat-value">{stats.avgTeamSize}</span>
              <span className="stat-label">Avg Size</span>
            </div>
            <div className="stat-item">
              <span className="stat-value">{stats.minTeamSize}-{stats.maxTeamSize}</span>
              <span className="stat-label">Size Range</span>
            </div>
          </div>
          
          {/* Department Distribution */}
          {Object.keys(stats.departmentDistribution).length > 1 && (
            <div className="department-distribution">
              <h5>Department Distribution:</h5>
              <div className="dept-stats">
                {Object.entries(stats.departmentDistribution).map(([dept, count]) => (
                  <span key={dept} className="dept-stat">
                    <strong>{dept}:</strong> {count}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Teams Grid */}
        <div className="teams-grid">
          {teams.map(team => {
            const captain = getTeamCaptain(team);
            
            return (
              <div key={team.id} className="team-card">
                
                {/* Team Header */}
                <div className="team-header">
                  <div className="team-info">
                    <h4 className="team-name">{team.name}</h4>
                    <span className="member-count">{team.members?.length || 0} members</span>
                  </div>
                  <div className="team-id">#{team.id}</div>
                </div>

                {/* Team Captain */}
                {captain && (
                  <div className="team-captain">
                    <span className="captain-badge">Captain</span>
                    <div className="captain-info">
                      <div className="captain-name">{captain.display_name || captain.username}</div>
                      <div className="captain-department">{captain.department}</div>
                    </div>
                  </div>
                )}

                {/* Team Members List */}
                <div className="team-members">
                  <ul className="members-list">
                    {(team.members || []).map(member => (
                      <li key={member.id} className={`team-member ${member.id === team.leader_id ? 'is-captain' : ''}`}>
                        <div className="member-info">
                          <div className="member-name">
                            {member.display_name || member.username}
                            {member.id === team.leader_id && (
                              <span className="captain-indicator">👑</span>
                            )}
                          </div>
                          <div className="member-department">{member.department}</div>
                          <div className="member-username">@{member.username}</div>
                        </div>
                      </li>
                    ))}
                  </ul>
                </div>
                
              </div>
            );
          })}
        </div>

        {/* Footer Info */}
        <div className="display-footer">
          <div className="footer-info">
            <small>
              Teams created by backend algorithm • 
              Stored in database • 
              Captains assigned based on configuration rules
            </small>
          </div>
        </div>

      </div>
    </div>
  );
};

export default TeamDisplay;