/**
 * Component: TeamDisplay.jsx
 * Purpose: Display generated teams from backend API with proper captain display
 * Part of: Easter Quest 2025 Team Creation
 * Location: frontend/src/components/TeamCreation/TeamDisplay.jsx
 * 
 * Features:
 * - Display teams generated by backend algorithm
 * - Show team members with departments
 * - Highlight team captain (FIXED)
 * - Team statistics summary
 * - Export teams to CSV via API service
 * - Empty state when no teams exist
 * 
 * Data Structure Expected from Backend:
 * teams: [{
 *   id: number,
 *   name: string,
 *   leader_id: number,  // Backend uses leader_id, not captain_id
 *   members: [{id, username, display_name, department, is_captain}]
 * }]
 * 
 * FIXED ISSUES:
 * - Captain display now works with backend leader_id field
 * - Proper fallback when captain data is missing
 * - Consistent captain highlighting in member list
 * 
 * @since 2025-08-31
 * @updated 2025-09-03 - Fixed captain display logic
 */

import React, { useState } from 'react';
import api from '../../services/api';

const TeamDisplay = ({ teams, players, showNotification, useMock = false }) => {
  const [exportLoading, setExportLoading] = useState(false);

  // SECURITY: Filter out system teams (is_system_team=true) from display
  const displayTeams = teams ? teams.filter(team => !team.is_system_team) : [];

  // ---- DEBUG LOG START ----
  console.log("DEBUG: Received teams from backend:", teams);
  console.log("DEBUG: Display teams (filtered):", displayTeams);
  if (displayTeams && displayTeams.length > 0) {
    displayTeams.forEach(team => {
      console.log(`Team: ${team.name} (ID: ${team.id}, Leader ID: ${team.leader_id})`);
    });
  }
  // ---- DEBUG LOG END ----

  /**
   * Calculate team statistics from real backend data
   */
  const calculateStats = () => {
    if (!displayTeams || displayTeams.length === 0) {
      return {
        totalTeams: 0,
        totalPlayers: 0,
        avgTeamSize: 0,
        minTeamSize: 0,
        maxTeamSize: 0,
        departmentDistribution: {}
      };
    }

    const totalPlayers = displayTeams.reduce((sum, team) => sum + (team.members?.length || 0), 0);
    const teamSizes = displayTeams.map(team => team.members?.length || 0);
    const minTeamSize = Math.min(...teamSizes);
    const maxTeamSize = Math.max(...teamSizes);
    const avgTeamSize = totalPlayers > 0 ? (totalPlayers / displayTeams.length) : 0;

    // Calculate department distribution
    const departmentDistribution = {};
    displayTeams.forEach(team => {
      (team.members || []).forEach(member => {
        const dept = member.department || 'Unassigned';
        departmentDistribution[dept] = (departmentDistribution[dept] || 0) + 1;
      });
    });

    return {
      totalTeams: displayTeams.length,
      totalPlayers,
      avgTeamSize: Math.round(avgTeamSize * 10) / 10,
      minTeamSize,
      maxTeamSize,
      departmentDistribution
    };
  };

  /**
   * Handle CSV export via backend API
   */
  const handleExportCSV = async () => {
    if (!displayTeams || displayTeams.length === 0) {
      showNotification('No teams to export', 'warning');
      return;
    }

    setExportLoading(true);
    
    try {
      const csvData = await api.teams.export();
      
      // Create and download CSV file
      const blob = new Blob([csvData], { type: 'text/csv;charset=utf-8' });
      const link = document.createElement('a');
      const url = URL.createObjectURL(blob);
      
      link.href = url;
      link.download = `team-assignments-${new Date().toISOString().split('T')[0]}.csv`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      showNotification('Teams exported successfully', 'success');
      
    } catch (error) {
      api.utils.handleError(error, showNotification);
    } finally {
      setExportLoading(false);
    }
  };

  /**
   * Check if member is captain - FIXED VERSION
   * Backend uses leader_id field, not captain_id
   */
  const isCaptain = (member, team) => {
    return team.leader_id && member.id === team.leader_id;
  };

  const stats = calculateStats();

  // Empty state - no teams generated yet
  if (!teams || teams.length === 0) {
    return (
      <div className="card">
        <div className="card-header">
          <h3 className="card-title">Generated Teams</h3>
        </div>
        <div className="card-body">
          <div className="empty-state">
            <div className="empty-icon">🎲</div>
            <h4>No Teams Created Yet</h4>
            <p>Configure your team settings and click "Create Teams" to generate teams using the backend algorithm.</p>
            <div className="empty-hints">
              <small>Steps:</small>
              <ul>
                <li>Upload players using CSV file</li>
                <li>Configure team size and department constraints</li>
                <li>Backend will create balanced teams automatically</li>
                <li>Captains assigned based on your rules</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="card">
      <div className="card-header">
        <div className="card-title-section">
          <h3 className="card-title">Generated Teams ({teams.length})</h3>
          <div className="header-actions">
            <button
              className="btn-header-action"
              onClick={handleExportCSV}
              disabled={exportLoading}
            >
              {exportLoading ? '⏳ Exporting...' : '📥 Export CSV'}
            </button>
          </div>
        </div>
      </div>

      <div className="card-body">
        
        {/* Team Statistics */}
        <div className="team-stats">
          <h4>Team Statistics</h4>
          <div className="stats-grid">
            <div className="stat-item">
              <span className="stat-value">{stats.totalTeams}</span>
              <span className="stat-label">Teams</span>
            </div>
            <div className="stat-item">
              <span className="stat-value">{stats.totalPlayers}</span>
              <span className="stat-label">Players</span>
            </div>
            <div className="stat-item">
              <span className="stat-value">{stats.avgTeamSize}</span>
              <span className="stat-label">Avg Size</span>
            </div>
            <div className="stat-item">
              <span className="stat-value">{stats.minTeamSize}-{stats.maxTeamSize}</span>
              <span className="stat-label">Size Range</span>
            </div>
          </div>
          
          {/* Department Distribution */}
          {Object.keys(stats.departmentDistribution).length > 1 && (
            <div className="department-distribution">
              <h5>Department Distribution:</h5>
              <div className="dept-stats">
                {Object.entries(stats.departmentDistribution).map(([dept, count]) => (
                  <span key={dept} className="dept-stat">
                    <strong>{dept}:</strong> {count}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Teams Grid */}
        <div className="teams-grid">
          {displayTeams.map(team => (
              <div key={team.id} className="team-card">
                
                {/* Team Header */}
                <div className="team-header">
                  <div className="team-info">
                    <h4 className="team-name">{team.name}</h4>
                    <span className="member-count">{team.members?.length || 0} members</span>
                  </div>
                </div>

                {/* Team Members List - CLEAN VERSION */}
                <div className="team-members">
                  <h5 className="members-header">Team Members:</h5>
                  {(team.members || []).length === 0 ? (
                    <div className="no-members">No members assigned</div>
                  ) : (
                    <ul className="members-list">
                      {team.members.map(member => {
                        const memberIsCaptain = isCaptain(member, team);
                        
                        return (
                          <li 
                            key={member.id} 
                            className={`team-member ${memberIsCaptain ? 'is-captain' : ''}`}
                          >
                            <div className="member-info">
                              <div className="member-name">
                                {member.display_name || member.username}
                                {memberIsCaptain && (
                                  <span className="status-badge captain-badge" style={{marginLeft: '0.5rem', fontSize: '0.75rem'}}>
                                    👑 Captain
                                  </span>
                                )}
                              </div>
                              <div className="member-department">{member.department || 'No Department'}</div>
                              <div className="member-username">{member.username}</div>
                            </div>
                          </li>
                        );
                      })}
                    </ul>
                  )}
                </div>

              </div>
          ))}
        </div>

        {/* Footer Info */}
        <div className="display-footer">
          <div className="footer-info">
            <small>
              Teams created by backend algorithm • 
              Stored in database • 
              Captains assigned based on configuration rules • 
              Captain display: FIXED
            </small>
          </div>
        </div>

      </div>
    </div>
  );
};

export default TeamDisplay;